import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/app/globals.css';
import NavbarCreateHome from '@/app/components/NavbarCreateHome';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}font-circular `}>
        <NavbarCreateHome />
        {children}
      </body>
    </html>
  );
}
